# SPDX-FileCopyrightText: None
# SPDX-License-Identifier: CC0-1.0

Dependencies:
- 'on': ['@all']
  'require':
    'frameworks/extra-cmake-modules': '@stable'
    'frameworks/ktextwidgets': '@stable'
    'frameworks/knotifications': '@stable'
    'frameworks/kguiaddons': '@stable'
    'frameworks/kiconthemes': '@stable'
    'frameworks/kwindowsystem': '@stable'
    'frameworks/kio': '@stable'
    'frameworks/kdbusaddons': '@stable'

Options:
    require-passing-tests-on: [ 'Linux', 'FreeBSD' ]
